##
## -------------------------
## |    JELLYFIN-STACK     |
## -------------------------
##

version: "3.3"
services:

  # ----------------------------------------
  #               VPN DIY                  |
  # ----------------------------------------
  vpn:
    container_name: custom-vpn
    build: 
      context: .
      dockerfile: ./Dockerfile 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./vpn/vpn-config/config.ovpn:/etc/openvpn/config.ovpn
      - ./vpn/vpn-config/credentials.txt:/etc/openvpn/credentials.txt
    restart: always
    networks:
      - vpn_network


  # ----------------------------------------
  #                DELUGE                  |
  # ----------------------------------------
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      - DELUGE_USER=deluge
      - DELUGE_PASS=deluge
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH}/configs/deluge:/config
      - ${COMMON_PATH}/deluge/downloads:/downloads
    restart: unless-stopped

   
  # ----------------------------------------
  #             Flaresolverr               |
  # ----------------------------------------      
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      - vpn_network


  # ----------------------------------------
  #               PROWLARR                 |
  # ----------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH}/configs/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - vpn_network


  # ----------------------------------------
  #                JACKETT                 |
  # ----------------------------------------
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH}/configs/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - vpn_network


  # ----------------------------------------
  #                SONARR                  |
  # ----------------------------------------
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH}:${COMMON_PATH}
      - ${COMMON_PATH}/configs/sonarr:/config
      - ${COMMON_PATH}/sonarr/tv:/tv
      - ${COMMON_PATH}/deluge/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - vpn_network


  # ----------------------------------------
  #                  RADARR                |
  # ----------------------------------------
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH}:${COMMON_PATH}
      - ${COMMON_PATH}/configs/radarr:/config
      - ${COMMON_PATH}/radarr/movies:/movies
      - ${COMMON_PATH}/deluge/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - vpn_network


  # ----------------------------------------
  #               JELLYFIN                 |
  # ----------------------------------------
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - ${COMMON_PATH}:${COMMON_PATH}
      - ${COMMON_PATH}/configs/jellyfin:/config
      - ${COMMON_PATH}/jellyfin/cache:/cache
      - ${COMMON_PATH}/sonarr/tv:/data/tvshows
      - ${COMMON_PATH}/radarr/movies:/data/movies
      - ${COMMON_PATH}/deluge/downloads:/data/media_downloads
    restart: unless-stopped
    networks:
      - vpn_network


  # ----------------------------------------
  #               JELYSEERR                |
  # ----------------------------------------
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ${COMMON_PATH}/configs/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - vpn_network

networks:
  vpn_network:
    driver: bridge
